server.port=8090

# OAuth2 Related
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/adminapps/protocol/openid-connect/certs

# =========================
# DEBUG LOGGING (add this)
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http=DEBUG