server:
  port: 8082

spring:
  cloud:
    gateway:
      mvc: # THIS IS MANDATORY FOR THE WEBMVC STARTER
        routes:
          - id: users-status-check
            uri: http://localhost:8081
            predicates:
              - Path=/users/status/check
              - Method=GET
            filters:
              - RemoveRequestHeader=Cookie